### ISSUE TITLE
We can't make a base of islands_engine following "islands_interface." 

### ISSUE THREAD

**Issue by MickeyOoh** [MickeyOoh/islands_engine#1]
When "islands_interface" is under this, islands_engine and set the deps islands_interface.
```
defp deps do
[ {:islands_interface, path: "../islands_interface"}]

# config/config.exs
import_config "../../islands_interface/config/config.exs"
```
on the other hand, I deleted 
```
{:islands_engine, path: "../islands_engine"}
```
in _interface mix.exs
So base switched islands_interface to _engine. 
In this case, Error come out:
```
== Compilation error in file lib/islands_interface_web/endpoint.ex ==
** (UndefinedFunctionError) function Phoenix.LiveReloader.init/1 is undefined (module Phoenix.LiveReloader is not available)
    Phoenix.LiveReloader.init([])
    (plug) lib/plug/builder.ex:214: Plug.Builder.init_module_plug/4
    (plug) lib/plug/builder.ex:198: anonymous fn/5 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:196: Plug.Builder.compile/3
    (plug) expanding macro: Plug.Builder.__before_compile__/1
    lib/islands_interface_web/endpoint.ex:1: IslandsInterfaceWeb.Endpoint (module)
```
**Then it didn't work.**

**Comment by MickeyOoh** [comment]
I copy the config definitions in islands_interface/config/config.exs into islands_engine/config/config.exs.
the above error doesn't come out anymore. 
** What happens to this as it must be the same? **

## But phoenix Server don't work.

**Comment by MickeyOoh** [comment]
There are some configuration files in islands_interface/config; prod.exs, dev.exs, test.exs and prod.sercret.exs.
So I should import all configurations files from islands_engine. Otherwise it won't be the same environment configuration of phx.server.
